config/routes.rb
Rails.application.routes.draw do
  resources :wikis
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name_type, presence: true, uniqueness: true
    has_many :wikis
end

app/models/wiki.rb
class Wiki < ApplicationRecord
    validates :category_id, presence: true
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :current_wiki, only: [:show, :edit, :update, :destroy]
  before_action :set_categories
  def index
    @wikis = Wiki.all
  end

  def show

  end

  def new
    @wiki = Wiki.new
  end

  def create
    wiki = Wiki.create(wiki_params)

    redirect_to wiki_path(wiki)
  end

  def edit

  end

  def update
    @wiki = Wiki.find(params[:id])

    @wiki.update(wiki_params)

    redirect_to wiki_path(@wiki)
  end

  def destroy
    @wiki.destroy

    redirect_to wikis_path
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :description, :kind, :author, :category_id)
  end

  def current_wiki
    @wiki = Wiki.find(params[:id])
  end

  def set_categories
    @categories = Category.all.order(:name_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>  
<html>  
  <head>  
      <title>Myapp</title>  
      <meta name="viewport" content="width=device-width,initial-scale=1">  
      <%= csrf_meta_tags %>  
      <%= csp_meta_tag %>  
      
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
      <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>  
  </head>  
  
  <body>  
    <%= yield %>  
  </body>  
</html>  

app/views/wikis/edit.html.erb
<div class="container">
  <h3>Update Wiki Details</h3>
  
    <%= form_with model: @wiki do |form| %>
    <div class="col">
      <%= form.text_field :title, placeholder: "title", :class => "form-control" %>
      <%= form.text_field :description, placeholder: "description", :class => "form-control" %>
      <%= form.text_field :kind, placeholder: "kind", :class => "form-control" %>
      <%= form.text_field :author, placeholder: "author", :class => "form-control" %>
      <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name_type, cat.id]}), :class => "form-select"%>
      <%= form.submit%>
    </div>
    <% end %>
  
  <%= link_to sanitize("&larr; Back to home"), wikis_path, :class => "btn btn-success"%>
</div>

app/views/wikis/index.html.erb
<div class="container">
	<table>
		<% @wikis.each do |wiki| %>
			<tr>
			<td><%= link_to wiki.title, wiki_path(wiki) %></td>
			<td><%= button_to 'Edit', edit_wiki_path(wiki), method: 'get', :class => "btn btn-primary btn-sm"%></td>
			<td><%= button_to 'Remove', wiki_path(wiki), method: 'delete', data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %></td>
		<% end %>
	</table>
	<%= link_to "Add a New Wiki", new_wiki_path, :class => "btn btn-success" %>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <h3>Create a Wiki</h3>
  
    <%= form_with model: @wiki do |form| %>
    <div class="col">
      <%= form.text_field :title, placeholder: "title", :class => "form-control" %>
      <%= form.text_field :description, placeholder: "description", :class => "form-control" %>
      <%= form.text_field :kind, placeholder: "kind", :class => "form-control" %>
      <%= form.text_field :author, placeholder: "author", :class => "form-control" %>
      <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name_type, cat.id]}), :class => "form-control"%>
      <%= form.submit %>
    </div>
    <% end %>
  
  <%= link_to sanitize("&larr; Back to home"), wikis_path, :class => "btn btn-success"%>
</div>

app/views/wikis/show.html.erb
<div class="container">
    <h1><%= @wiki.title %></h1>
    <h4><%= @wiki.description %></h4>
    <h4><%= @wiki.kind %></h4>
    <h4><%= @wiki.author %></h4>
    <h4><%= @wiki.category.name_type %></h4>
    <br/>
    <br/>

    <%= link_to sanitize("&larr; Back to home"), wikis_path, :class => "btn btn-success"%>
</div>